meta_product_name: "Dori"
meta_title: "Organisez vos séances de piscines à Paris"
meta_description: "Créer votre propre programme d'entrainement directement dans votre agenda"
meta_image: "poolopengraph.jpg"
